### ISSUE TITLE
Crash during report generation when running with Singularity

### ISSUE THREAD

**Issue by boulund** [ctmrbio/stag-mwc#160]
Steffi reported:
```
snakemake: error: argument --singularity-args: expected one argument
CalledProcessError in line 157 of /home/stefanie.prast/projects/ep/StaG/stag-mwc/Snakefile:
Command 'set -euo pipefail;  /ctmr/anaconda/anaconda3/bin/snakemake --use-singularity --singularity-prefix /ctmr/stag_envs --singularity-args -B /db,/home/stefanie.prast/projects/ep/rawdata_MiSeq11to13 --jobs 30 --unlock' returned non-zero exit status 2.
  File "/home/stefanie.prast/projects/ep/StaG/stag-mwc/Snakefile", line 157, in __onsuccess
```

@AroArz, you've run StaG a lot with Singularity, have you ever encountered this before? It appears it is caused by this line:
https://github.com/ctmrbio/stag-mwc/blob/develop/Snakefile#L157

I guess the singularity-args argument, when given on the command line, is lexed differently to when we in the Snakefile just merge all the arguments into a single string on line 156. In this particular case, the snakemake command was invoked on the command line as this:
```
snakemake --use-singularity --singularity-prefix /ctmr/stag_envs --singularity-args "-B /db,/home/stefanie.prast/projects/ep/rawdata_MiSeq11to13" --jobs 30
```
Note the quoted argument to `--singularity-args`.

**Comment by AroArz** [comment]
I have had all sorts of problems with snakemake and singularity for unknown reasons. Which version of Snakemake and what branch in StaG was used? I typically don't use `--singularity-prefix` but maybe the issue is raised because the --singularity-prefix is not included in the bind path?

**Comment by boulund** [comment]
She was running the latest develop branch. We needed to use `--singularity-prefix` to specify bind paths for database and input files (symlinks in `input` directory were pointing out of the workdir). 

It created the report just fine after executing a plain `snakemake` command afterwards without any arguments (then running only report generation on a single core as all rules had already been executed successfully).

Just curious if you had ever encountered it @AroArz . I guess we will have to figure out a way to make the hacky automatic report generation a bit more robust :)

**Comment by AroArz** [comment]
Ah alright, then I understand. I thought the pipeline didn't start at all. I've had that problem every time I run with singularity. I mentioned it to you sometime last year but put it on the back burner after I realised it can be circumvented with plain `snakemake`. 

I feel like just changing 

`        shell("{snakemake_call} --report {report}-{datetime}.html".format(`
to
`        shell("snakemake --report {report}-{datetime}.html".format(`

might fix the problem? I can't test right now because Rackham is down...

**Comment by boulund** [comment]
Sure, that could be a quick way to solve that. The report generation should be able to run using a single core in the calling environment without issues I guess. Do you think there could be any problems during report generation that requires additional packages that cannot be expected to be installed in the calling environment?

**Comment by AroArz** [comment]
The only issue that I've experience with report generation using plain `snakemake` is if you're trying to create it without internet. Aside from that, if you have loaded snakemake from a module it might crash because it doesn't have `pygraphviz` but I think that is normally downloaded and installed together with snakemake nowadays.

**Comment by boulund** [comment]
Ok, good. That sounds to me like this is the way to solve this then. Should we make an assumption that snakemake is available as just `snakemake` or pull it out of the call used (i.e. like `{snakemake_call[0]} --report ...`) ?

**Comment by AroArz** [comment]
I can't think of any scenario where the outcome will be different? However `{snakemake_call[0]} --report ...)` looks cleaner and more consistent when reading the code in my opinion.

**Comment by boulund** [comment]
Maybe the "correct" way to do this is to use `shlex.split` ? https://docs.python.org/3/library/shlex.html
