### ISSUE TITLE
Humann2 creates huge temp files in output folder

### ISSUE THREAD

**Issue by lis4matilda** [ctmrbio/stag-mwc#75]
Redirect temporary files from humann2 to tmp folder. On Uppmax the nodes tmp folder is called [$SNIC_TMP](https://www.uppmax.uu.se/support/user-guides/rackham-user-guide/).

**Comment by boulund** [comment]
This is apparently a known issue in HUMAnN2: https://bitbucket.org/biobakery/humann2/issues/16/reducing-temporary-file-size

Some information about it in the HUMAnN2 docs here: https://bitbucket.org/biobakery/humann2/wiki/Home#markdown-header-4-intermediate-temp-output-files, but I can't see a simple way to change the directory used for temporary files :(

**Comment by boulund** [comment]
I tried fixing this by forking HUMAnN2 and modifying the source code, making the changes seen in this commit: https://bitbucket.org/boulund/humann2/commits/18588fc82dc9c8c57b48ac51608a33a0f58a9f94?at=allow-set-temp-dir

Then, installing it into the `biobakery.yaml` environment file like this:

```
name: stag-mwc-biobakery
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - metaphlan2 =2.7.8
    - krona =2.7
    - pip:
        - hg+https://bitbucket.org/boulund/humann2@allow-set-temp-dir#egg=humann2
```

However, it seems it didn't make a difference at all... Not sure what happened. Happy if someone else could test this in a more controlled setting to see what's going on.

**Comment by boulund** [comment]
I'm planning to clean up my private fork of HUMAnN2 a bit, including:

- Figure out this thing with temporary directory specification, so we can rid ourselves of the issues with huge temp files in the output folder (filling up HPC project storage quota during run, and slowing things down because everything ends up in the shared filesystem).
- Remove all baggage in the repo, I expect this to reduce the repo size by about very large amount (maybe even 1GB?), speeding up environment creation substantially

**Comment by boulund** [comment]
No longer relevant. Humann3 still creates huge temporary files, but it's kind of handled.
